# Generated by Django 5.1.4 on 2025-02-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_feedbackdata_created_by_feedbackdata_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackdata",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Admin note for the feedback",
                null=True,
                verbose_name="Note",
            ),
        ),
    ]
