# Generated by Django 5.1.4 on 2025-01-01 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFile",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date updated",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="Hidden"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang xử lý"),
                            ("done", "Đã hoàn thành"),
                            ("error", "Có lỗi"),
                        ],
                        default="done",
                        max_length=25,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("upload", "Tải lên"), ("auto", "Tự động")],
                        default="upload",
                        max_length=25,
                        verbose_name="Phương thức",
                    ),
                ),
                ("file", models.FileField(upload_to="excels")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tệp Excel",
                "verbose_name_plural": "Tệp Excel",
            },
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date updated",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="Hidden"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang xử lý"),
                            ("done", "Đã hoàn thành"),
                            ("error", "Có lỗi"),
                        ],
                        default="done",
                        max_length=25,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("upload", "Tải lên"), ("auto", "Tự động")],
                        default="upload",
                        max_length=25,
                        verbose_name="Phương thức",
                    ),
                ),
                ("file", models.FileField(upload_to="pdfs")),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tệp PDF",
                "verbose_name_plural": "Tệp PDF",
            },
        ),
    ]
