# Generated by Django 5.1.4 on 2025-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="excelfile",
            options={
                "verbose_name": "Excel File",
                "verbose_name_plural": "Excel Files",
            },
        ),
        migrations.AlterModelOptions(
            name="pdffile",
            options={"verbose_name": "PDF File", "verbose_name_plural": "PDF Files"},
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="method",
            field=models.CharField(
                choices=[("upload", "Upload"), ("auto", "Auto")],
                default="upload",
                max_length=25,
                verbose_name="Method",
            ),
        ),
        migrations.AlterField(
            model_name="excelfile",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done"), ("error", "Error")],
                default="done",
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="method",
            field=models.CharField(
                choices=[("upload", "Upload"), ("auto", "Auto")],
                default="upload",
                max_length=25,
                verbose_name="Method",
            ),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("done", "Done"), ("error", "Error")],
                default="done",
                max_length=25,
                verbose_name="Status",
            ),
        ),
    ]
